# Generated by Django 5.0.1 on 2025-10-11 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_status_project_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Key_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Icon', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.service')),
            ],
        ),
    ]
