# Generated by Django 5.0.1 on 2025-10-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_service_key_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_key_feature',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service_key_feature',
            old_name='Icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='service_key_feature',
            old_name='Title',
            new_name='title',
        ),
    ]
