# Generated by Django 5.0.1 on 2025-10-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_description_service_key_feature_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='aboutus',
            field=models.TextField(blank=True, max_length=1255, null=True),
        ),
    ]
