# Generated by Django 5.0.1 on 2025-10-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_service_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usp_line',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
