# Generated by Django 5.0.1 on 2025-10-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Recommended_For_You',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='Top_Deals_Of_The_Day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='Top_Selling_Products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_project',
            field=models.BooleanField(default=False),
        ),
    ]
