# Generated by Django 5.0.1 on 2025-10-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_category_recommended_for_you_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
