# Generated by Django 5.0.1 on 2025-10-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_contact_updated_at_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('graduation_year', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=200)),
                ('entrance_exam', models.CharField(max_length=200)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
