# Generated by Django 5.0.1 on 2025-09-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '10. Gallery'},
        ),
    ]
