# Generated by Django 5.0.1 on 2025-09-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_gallery_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='MediaGallery',
        ),
    ]
