# Generated by Django 5.0.1 on 2025-10-12 12:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_review_delete_contactmessage_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy')], help_text='Select which legal page this is.', max_length=20, unique=True)),
                ('title', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(help_text='URL slug, auto from title recommended.', max_length=170, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary for meta/preview (optional).')),
                ('content', ckeditor.fields.RichTextField(help_text='Full rich text content.')),
                ('is_published', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['page'],
            },
        ),
    ]
