# Generated by Django 5.0.1 on 2025-10-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_legal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Legal',
        ),
    ]
