# Generated by Django 5.0.1 on 2025-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_full_time_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_time_program',
            name='Image',
        ),
        migrations.AddField(
            model_name='full_time_program',
            name='image',
            field=models.ImageField(blank=True, upload_to='Programe/'),
        ),
    ]
