# Generated by Django 5.0.1 on 2025-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_online_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='About_bg',
            field=models.ImageField(blank=True, upload_to='aboutus/'),
        ),
    ]
