# Generated by Django 5.0.1 on 2025-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_setting_about_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='services_hero',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
    ]
