# Generated by Django 5.0.1 on 2025-10-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_call_status_city_find_form_googlemap_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
