# Generated by Django 5.0.1 on 2025-10-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_graduation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
