# Generated by Django 5.0.1 on 2025-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
