# Generated by Django 5.0.1 on 2025-10-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_alter_specialization_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance_Exams_Appeared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
