# Generated by Django 5.0.1 on 2025-10-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_entrance_exams_appeared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=200, unique=True)),
                ('From', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
