# Generated by Django 5.0.1 on 2025-10-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_time_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_select',
            old_name='From',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='time_select',
            name='To',
        ),
    ]
