# Generated by Django 5.0.1 on 2025-10-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_rename_from_time_select_time_remove_time_select_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_select',
            old_name='Time',
            new_name='time',
        ),
    ]
