# Generated by Django 5.0.1 on 2025-10-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_rename_time_time_select_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='Blog/')),
                ('Desciription', models.CharField(max_length=200, unique=True)),
                ('read_more_content', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
